[package]
name = "medieval"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.19"
derive_more = {version = "2.1.1", features = ["add", "mul", "from"] }
image = { version = "0.25", default-features = false, features = ["png"] }
noise = "0.9.0"
rand = { version = "=0.10.2", features = ["chacha"] }
time = { version = "0.3.55", features = ["formatting", "macros"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "time"] }

[dev-dependencies]
approx = "0.5.1"
divan = "0.1.21"
rstest = "0.26.1"

[[bench]]
name = "hex_length"
harness = false
